name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - name: Build website
        run: |
          sudo apt-get install -y python-pygments racket
          sudo make all
          sudo git config --global user.name "github-actions[bot]"
          sudo git config --global user.email "nuprl+github-actions[bot]@users.noreply.github.com"
          sudo git add -A -f
          sudo git checkout -b "deploy"
          sudo git commit --allow-empty -m "** deploy nuprl/website@$GITHUB_SHA"
          sudo git push origin deploy -f
