name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      
      - uses: actions/checkout@v2
      - name: Build website
        run: |
          sudo apt-get install -y python-pygments
          ./install.sh
          make all
          git config --global user.name "github-actions[bot]"
          git config --global user.email "nuprl+github-actions[bot]@users.noreply.github.com"
          git add -A -f
          git checkout -b "deploy"
          git commit --allow-empty -m "** deploy nuprl/website@$GITHUB_SHA"
          git push origin deploy -f
