name: PRCheck
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      - name: Build website
        run: |
          sudo apt-get install -y python-pygments racket
          sudo make all
